[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "financial-product-complaint"
version = "v0.0.1"
authors = [{name = "Chandra Reddy Tiyyagura", email = "tchandrareddy21@gmail.com"}]
description = "Complaints can give us insights into problems people are experiencing in the marketplace and help us to undestand the reason and do necessary modification in exisiting financial product if required."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.38.13",
    "pandas>=2.2.3",
    "pymongo[srv]>=4.12.1",
    "pyspark>=3.5.5",
    "python-dotenv>=1.1.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]


[tool.setuptools]
package-dir = {"" = "finance"}
include-package-data = true

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "jupyterlab>=4.4.2",
]
